/**
 * Markdown Export Utility
 * Converts journeys to markdown format for easy export and sharing
 */

import type { Journey, Stage } from '../types';

/**
 * Convert a journey to markdown format
 */
export function journeyToMarkdown(journey: Journey): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${journey.input}`);
  lines.push('');
  lines.push(`**Status:** ${journey.status}`);
  lines.push(`**Created:** ${new Date(journey.createdAt).toLocaleString()}`);
  lines.push(`**Updated:** ${new Date(journey.updatedAt).toLocaleString()}`);
  lines.push(`**Stages:** ${journey.stages.length}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Settings
  lines.push('## Journey Settings');
  lines.push('');
  lines.push(`- Auto Continue: ${journey.settings.autoContinue ? 'Yes' : 'No'}`);
  lines.push(`- Max Stages: ${journey.settings.maxStages}`);
  lines.push(`- Stage Delay: ${journey.settings.stageDelay}ms`);
  lines.push(`- Extended Thinking: ${journey.settings.extendedThinking ? 'Yes' : 'No'}`);
  lines.push(`- Computer Use: ${journey.settings.computerUse ? 'Yes' : 'No'}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Stages
  journey.stages.forEach((stage, index) => {
    lines.push(`## Stage ${index + 1}: ${formatStageType(stage.type)}`);
    lines.push('');
    lines.push(`**Status:** ${stage.status}`);
    lines.push(`**Created:** ${new Date(stage.createdAt).toLocaleString()}`);
    lines.push('');

    // Stage result
    if (stage.result) {
      lines.push('### Result');
      lines.push('');
      lines.push(stage.result);
      lines.push('');
    }

    // Extended thinking (if available)
    if (stage.thinking) {
      lines.push('### Extended Thinking');
      lines.push('');
      lines.push(stage.thinking);
      lines.push('');
    }

    // Artifacts
    if (stage.artifacts && stage.artifacts.length > 0) {
      lines.push(`### Artifacts (${stage.artifacts.length})`);
      lines.push('');

      stage.artifacts.forEach((artifact, artifactIndex) => {
        lines.push(`#### ${artifactIndex + 1}. ${artifact.title}`);
        lines.push('');
        lines.push(`**Type:** ${artifact.type}`);
        lines.push(`**Created:** ${new Date(artifact.createdAt).toLocaleString()}`);
        lines.push('');

        // Format artifact content based on type
        if (artifact.type === 'code') {
          const language = artifact.metadata?.language || '';
          lines.push(`\`\`\`${language}`);
          lines.push(artifact.content);
          lines.push('```');
        } else {
          lines.push(artifact.content);
        }

        lines.push('');
      });
    }

    lines.push('---');
    lines.push('');
  });

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Cognet - The Infinite Thought Engine*');
  lines.push('');

  return lines.join('\n');
}

/**
 * Format stage type for display
 */
function formatStageType(type: string): string {
  const typeMap: Record<string, string> = {
    discovering: '🔍 Discovering',
    chasing: '🎯 Chasing',
    solving: '💡 Solving',
    challenging: '⚡ Challenging',
    questioning: '❓ Questioning',
    searching: '🔎 Searching',
    imagining: '💭 Imagining',
    building: '🏗️ Building',
  };

  return typeMap[type] || type.charAt(0).toUpperCase() + type.slice(1);
}

/**
 * Download markdown content as a file
 */
export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate a safe filename from journey input
 */
export function generateMarkdownFilename(journey: Journey): string {
  // Take first 50 chars of input, remove special chars, replace spaces with hyphens
  const safeName = journey.input
    .substring(0, 50)
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');

  const timestamp = new Date(journey.createdAt).toISOString().split('T')[0];

  return `${safeName}-${timestamp}.md`;
}

/**
 * Export journey to markdown file
 */
export function exportJourneyToMarkdown(journey: Journey): void {
  const markdown = journeyToMarkdown(journey);
  const filename = generateMarkdownFilename(journey);
  downloadMarkdown(markdown, filename);
}
