/**
 * Core Type Definitions
 * Shared types across the application
 */
/**
 * Stage types in the exploration cycle
 */
export type StageType = 'discovering' | 'chasing' | 'solving' | 'challenging' | 'questioning' | 'searching' | 'imagining' | 'building';
/**
 * Journey status
 */
export type JourneyStatus = 'running' | 'paused' | 'stopped' | 'complete' | 'error';
/**
 * Stage status
 */
export type StageStatus = 'pending' | 'running' | 'complete' | 'error';
/**
 * Artifact types
 */
export type ArtifactType = 'document' | 'code' | 'visualization' | 'mindmap' | 'other';
/**
 * Journey - A complete exploration session
 */
export interface Journey {
    id: string;
    input: string;
    status: JourneyStatus;
    stages: Stage[];
    settings: JourneySettings;
    createdAt: number;
    updatedAt: number;
}
/**
 * Stage - A single step in the exploration cycle
 */
export interface Stage {
    id: string;
    journeyId: string;
    type: StageType;
    status: StageStatus;
    prompt: string;
    result: string;
    thinking?: string;
    artifacts: Artifact[];
    createdAt: number;
}
/**
 * Artifact - Output generated by a stage
 */
export interface Artifact {
    id: string;
    stageId: string;
    type: ArtifactType;
    title: string;
    content: string;
    metadata: {
        language?: string;
        framework?: string;
        tags?: string[];
        [key: string]: any;
    };
    createdAt: number;
}
/**
 * Journey settings
 */
export interface JourneySettings {
    autoContinue: boolean;
    maxStages: number;
    stageDelay: number;
    extendedThinking: boolean;
    computerUse: boolean;
}
/**
 * Default settings
 */
export declare const DEFAULT_SETTINGS: JourneySettings;
/**
 * Tag for categorizing journeys
 */
export interface Tag {
    id: string;
    name: string;
    color: string;
    createdAt: number;
}
/**
 * Application settings
 */
export interface AppSettings {
    theme: 'light' | 'dark' | 'system';
    apiKey?: string;
    autoSave: boolean;
    extendedThinking: boolean;
    computerUse: boolean;
}
/**
 * Database statistics
 */
export interface DatabaseStats {
    journeys: number;
    stages: number;
    artifacts: number;
}
/**
 * Health check response
 */
export interface HealthCheck {
    status: 'healthy' | 'unhealthy';
    database: boolean;
    fileSystem: boolean;
    timestamp: number;
}
/**
 * Error types
 */
export declare class CognetError extends Error {
    code: string;
    details?: any;
    constructor(message: string, code: string, details?: any);
}
/**
 * Type guards
 */
export declare function isStageType(value: any): value is StageType;
export declare function isJourneyStatus(value: any): value is JourneyStatus;
export declare function isArtifactType(value: any): value is ArtifactType;
//# sourceMappingURL=index.d.ts.map