/**
 * Core Type Definitions
 * Shared types across the application
 */

/**
 * Stage types in the exploration cycle
 */
export type StageType =
  | 'discovering'
  | 'chasing'
  | 'solving'
  | 'challenging'
  | 'questioning'
  | 'searching'
  | 'imagining'
  | 'building';

/**
 * Journey status
 */
export type JourneyStatus =
  | 'running'
  | 'paused'
  | 'stopped'
  | 'complete'
  | 'error';

/**
 * Stage status
 */
export type StageStatus = 'pending' | 'running' | 'complete' | 'error';

/**
 * Artifact types
 */
export type ArtifactType =
  | 'document'
  | 'code'
  | 'visualization'
  | 'mindmap'
  | 'other';

/**
 * Page types
 */
export type PageType = 'architect' | 'multi-agent' | 'template';

/**
 * Page metadata
 */
export interface PageMetadata {
  templateType?: 'report' | 'wiki' | 'presentation' | 'timeline' | 'mindmap' | 'website' | 'literature' | 'linkedin-content' | 'carousel';
  agents?: string[];
  generationTime?: number;
  [key: string]: unknown;
}

/**
 * Journey - A complete exploration session
 */
export interface Journey {
  id: string;
  input: string;
  status: JourneyStatus;
  stages: Stage[];
  settings: JourneySettings;
  createdAt: number;
  updatedAt: number;
}

/**
 * Stage - A single step in the exploration cycle
 */
export interface Stage {
  id: string;
  journeyId: string;
  type: StageType;
  status: StageStatus;
  prompt: string;
  result: string;
  thinking?: string;
  artifacts: Artifact[];
  createdAt: number;
  // Quality scoring metadata (Phase 2)
  qualityScore?: number; // Overall quality score 0-10
  qualityReport?: {
    overallScore: number;
    scores: {
      completeness: number;
      depth: number;
      specificity: number;
      actionability: number;
      coherence: number;
      novelty: number;
    };
    strengths: string[];
    weaknesses: string[];
    improvements: string[];
    shouldRevise: boolean;
    evaluatedAt: number;
  };
}

/**
 * Artifact - Output generated by a stage
 */
export interface Artifact {
  id: string;
  stageId: string;
  type: ArtifactType;
  title: string;
  content: string;
  metadata: {
    language?: string;
    framework?: string;
    tags?: string[];
    [key: string]: any;
  };
  createdAt: number;
}

/**
 * Page - Generated interactive HTML page from journey
 */
export interface Page {
  id: string;
  journeyId: string;
  type: PageType;
  templateName?: string;
  title: string;
  content: string;
  metadata?: PageMetadata;
  // File storage fields (Phase 2A)
  filePath?: string; // Relative path in page storage
  fileSize?: number; // Size in bytes
  analysisData?: string; // JSON-encoded JourneyAnalysis
  analysisTimestamp?: number; // When analysis was performed
  version?: number; // Version number for tracking updates
  createdAt: number;
}

/**
 * Journey settings
 */
export interface JourneySettings {
  autoContinue: boolean;
  maxStages: number;
  stageDelay: number; // ms between stages
  extendedThinking: boolean;
  computerUse: boolean;
}

/**
 * Default settings
 */
export const DEFAULT_SETTINGS: JourneySettings = {
  autoContinue: true,
  maxStages: 50,
  stageDelay: 2000,
  extendedThinking: true,
  computerUse: true,
};

/**
 * Tag for categorizing journeys
 */
export interface Tag {
  id: string;
  name: string;
  color: string;
  createdAt: number;
}

/**
 * Application settings
 */
export interface AppSettings {
  theme: 'light' | 'dark' | 'system';
  apiKey?: string;
  autoSave: boolean;
  extendedThinking: boolean;
  computerUse: boolean;
}

/**
 * Database statistics
 */
export interface DatabaseStats {
  journeys: number;
  stages: number;
  artifacts: number;
}

/**
 * Health check response
 */
export interface HealthCheck {
  status: 'healthy' | 'unhealthy';
  database: boolean;
  fileSystem: boolean;
  timestamp: number;
}

/**
 * Error types
 */
export class PerpetuaError extends Error {
  constructor(
    message: string,
    public code: string,
    public details?: any
  ) {
    super(message);
    this.name = 'PerpetuaError';
  }
}

/**
 * Type guards
 */
export function isStageType(value: any): value is StageType {
  return [
    'discovering',
    'chasing',
    'solving',
    'challenging',
    'questioning',
    'searching',
    'imagining',
    'building',
  ].includes(value);
}

export function isJourneyStatus(value: any): value is JourneyStatus {
  return ['running', 'paused', 'stopped', 'complete', 'error'].includes(value);
}

export function isArtifactType(value: any): value is ArtifactType {
  return ['document', 'code', 'visualization', 'mindmap', 'other'].includes(value);
}
